/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Session = IDL.Record({
  'mood' : IDL.Text,
  'frequencyHz' : IDL.Nat,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getUserSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'logSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Session = IDL.Record({
    'mood' : IDL.Text,
    'frequencyHz' : IDL.Nat,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getUserSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'logSession' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };